apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: abagdemo
  labels:
    purpose: loadgen
spec:
  containers:
  - name: loadgen
    image: radial/busyboxplus:curl
    command: ["/bin/sh"]
    args: 
    - '-c'
    - |
      while true; do 
        for x in 1 2 3 4 5; do
            curl abagdemo-svc.prod:5000/history/001
        done
        sleep 5
        for x in 1 2 3 4 5; do
            curl abagdemo-svc.prod:5000/history/002
        done
        sleep 5
      done
  restartPolicy: OnFailure
