# This was provides the Google Application Credentials so
# abagdemo can use Google Storage.
# Its the Key .json file from the Google Service Account.
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-gcp-creds
  labels:
    app: {{.Values.name}}
type: Opaque
data:
  {{.Values.gcpSecretFileName}}: "{{.Values.gcpSecretData}}"